<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
    <PackageReference Include="Neo.SmartContract.Testing" Version="3.5.0" />
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
  </ItemGroup>

  <ItemGroup>
    <NeoContractReference Include="..\ProxyTemplate\ProxyTemplate.csproj" />
  </ItemGroup>

</Project>
